server:
  port: 8010
spring:
  application:
    name: sob.blog_system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sob_blog_system?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: false
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 1
  data:
    solr:
      host: http://127.0.0.1:8983/solr/blog_core
# 我们使用docker来部署，这里的路径，应该是docker内部的路径
sob.blog.image.save-path: /root/docker/blog/uoload
# 2MB
sob.blog.image.max-size: 2097152
# 控制swagger的开关
sob.blog.swagger.enable: false